image:
  file: .gitpod.Dockerfile

ports:
  - port: 8787
    onOpen: open-preview

tasks:
  - init: |
      sudo apt-get update
      sudo apt-get install -y libxml2-dev libssl-dev libcurl4-openssl-dev libfontconfig1-dev
    command: |
      rstudio-server start
      echo "RStudio Server started on port 8787"
      echo "Install any additional R packages you need here"
